# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# bug 已修复 ../

site_name: 游戏和谐Wiki
site_url: https://ggame.gledos.science/
repo_url: https://github.com/gledos/ggame

theme:
  favicon: src/favicon.png
  font: false
  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到暗模式
    - media: "(prefers-color-scheme: dark)" 
      primary: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换到亮模式
  name: material
  language: zh # 中文，解决中文搜索问题
  features:
    # - search.highlight
      - navigation.instant # XHR 支持
      - navigation.indexes
      - header.autohide
      - navigation.top # 回到顶部的按钮
    # - toc.integrate
    # - tabs

use_directory_urls: false # gledos 不喜欢的 URL 风格，所以要关闭
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/ # 增加css-html样式，例如按钮，比如图片定义大小，caption
  - nl2br: false # newline-to-break markdown 非严格换行
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
  - admonition  # 突出显示一些东西，比如 !!!info|bug|tips之类
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes # 支持脚注[^1]
  - meta
  - def_list # 支持有序、无序、任务列表
  - pymdownx.tasklist
  # - pymdownx.arithmatex # 数学公式latex支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic  # 支持markdown高亮==，删除等高级样式
  - pymdownx.b64     # 将图片编码为 base64
  - pymdownx.details
  # - pymdownx.pathconverter:
  #     base_path: '' # default: ''
  #     relative_path: '' # default ''
  #     absolute: false # default: false
  #     tags: 'a script img link object embed'
  # - pymdownx.emoji:  # 支持图标icons和表情渲染，比如:smile:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.highlight    # 代码块相关
  - pymdownx.inlinehilite # 代码块相关
  - pymdownx.superfences  # 代码块相关
  - pymdownx.tabbed  # 标签页 https://squidfunk.github.io/mkdocs-material/reference/content-tabs/ # C++/python 代码例子切换
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
plugins:
  - search
  - abs-to-rel # 绝对路径转相对路径 https://pypi.org/project/mkdocs-abs-rel-plugin/
# - pdf-export # 导出为 PDF 格式，不过对于此 Wiki 来说，耗时过多。
# - roamlinks # 这是自动将链接转化为易于 mkdocs 的插件
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/gledos_microblogging
    - icon: material/email-outline
      link: mailto:cngledos@gmail.com

copyright: 使用了 <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a> 以及 Github Pages 生成并托管网站。<br>

